# ##############################################################################
# Dockerfile for libs
# ##############################################################################

ARG CLI_TAG
ARG DISTRO

FROM docker.io/open-kappa/arduino-cli:${CLI_TAG}-${DISTRO}

RUN arduino-cli config add board_manager.additional_urls \
        https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json \
        https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/releases/download/0.0.9/package_heltec_esp32_index.json \
    && arduino-cli update \
    && arduino-cli core install esp32:esp32@2.0.14 \
    && arduino-cli core install Heltec-esp32:esp32@0.0.9

RUN arduino-cli lib install "Adafruit ADS1X15@2.4.0" \
    && arduino-cli lib install "Adafruit BME280 Library@2.2.2" \
    && arduino-cli lib install "Adafruit BusIO@1.15.0" \
    && arduino-cli lib install "Adafruit SHTC3 Library@1.0.1" \
    && arduino-cli lib install "Adafruit SSD1306@2.5.9" \
    && arduino-cli lib install "Adafruit GFX Library@1.11.9" \
    && arduino-cli lib install "Adafruit Unified Sensor@1.1.12" \
    && arduino-cli lib install "Adafruit PN532@1.3.3" \
    && arduino-cli lib install "ADS1115_WE@1.5.0" \
    && arduino-cli lib install "ArduinoHttpClient@0.5.0" \
    && arduino-cli lib install "ArduinoJson@7.0.2" \
    && arduino-cli lib install "arduino-sht@1.2.3" \
    && arduino-cli lib install --git-url "https://github.com/me-no-dev/AsyncTCP.git#ca8ac5f919d02bea07b474531981ddbfd64de97c" \
    && arduino-cli lib install "BH1750@1.3.0" \
    && arduino-cli lib install --git-url "https://github.com/FStefanni/DFRobot_OzoneSensor.git#60d2b26fad0c8bb0b313d2b40c7ae3dcd5fb9d13" \
    && arduino-cli lib install "DHT sensor library@1.4.4" \
    && arduino-cli lib install --git-url "https://github.com/me-no-dev/ESPAsyncWebServer.git#f71e3d427b5be9791a8a2c93cf8079792c3a9a26" \
    && arduino-cli lib install "ESP32 I2C Slave@0.3.0" \
    && arduino-cli lib install "Heltec ESP32 Dev-Boards@1.1.5" \
    && arduino-cli lib install --git-url "https://github.com/FStefanni/LiquidCrystal_I2C.git" \
    && arduino-cli lib install "IRremoteESP8266@2.8.6" \
    && arduino-cli lib install "modbus-esp8266@4.1.0" \
    && arduino-cli lib install --git-url "https://gitlab.com/open-kappa/arduino/mqsensor.git" \
    && arduino-cli lib install --git-url "https://github.com/don/NDEF#838d3b68a62c5b95158b4ab4bdeabb3a5225001f" \
    && arduino-cli lib install "PCF8574@0.4.1" \
    && arduino-cli lib install --git-url "https://github.com/FStefanni/PN532" \
    && arduino-cli lib install "PubSubClient@2.8.0" \
    && arduino-cli lib install --git-url "https://github.com/FStefanni/sensirion-embedded-common.git" \
    && arduino-cli lib install --git-url "https://github.com/FStefanni/sensirion-embedded-sht-lib.git" \
    && arduino-cli lib install --git-url "https://github.com/FStefanni/sensirion-embedded-sps.git" \
    && arduino-cli lib install "SparkFun SCD30 Arduino Library@1.0.20" \
    && arduino-cli lib install "SparkFun u-blox GNSS Arduino Library@2.2.25" \
    && arduino-cli lib install "StreamDebugger@1.0.1" \
    && arduino-cli lib install --git-url "https://github.com/paulvha/svm30#9ee919165650f3d452b08749ec5ec339519848ab" \
    && arduino-cli lib install "TinyGSM@0.11.7"

# Patching Heltec issues:
COPY ./scripts/patch_heltec.sh /home/arduino/patch_heltec.sh
RUN ./patch_heltec.sh
